import { getActiveTournament } from "../../repositories/tournament-repository.js";
import { getTournamentRounds,getMatchesForRound } from "../../repositories/matches-repository.js";
import { getMyPredictions,savePrediction } from "../../repositories/predictions-repository.js";
import { getActiveScoreRules,getMyMatchBonusPicks,setMatchBonusPick,getMatchPointsMatrix } from "../../repositories/tips-extras-repository.js";
import { getAuthSnapshot } from "../../services/auth-service.js";
import { formatKickoff } from "../../utils/format.js";
import { countryCodeToFlag } from "../../utils/flag.js";
let state={tournament:null,rounds:[],selectedRoundId:null,matches:[],predictions:new Map(),bonusPicks:new Map(),scoreRules:[],saving:new Set(),timers:new Map()};
const key=(id,c)=>`${id}:${c}`;const count=c=>[...state.bonusPicks].filter(([k,v])=>v&&k.endsWith(`:${c}`)).length;const open=(m,r)=>m.status==="scheduled"&&r?.status==="open"&&Date.now()<new Date(m.tipping_closes_at||r?.closes_at||m.kickoff_at).getTime();const tier=n=>`<span class="tips-tier tips-tier--${n}">T${n}</span>`;
function prow(label,type,v,active){return `<div class="points-explainer__row ${active?"is-active":""}"><span><strong>${label}</strong><small>${type}</small></span><b><em>Utfall</em>${v.outcome}</b><b><em>Diff</em>${v.difference}</b><b><em>Eksakt</em>${v.exact}</b></div>`}
function explain(m,p){const x=getMatchPointsMatrix(m,state.scoreRules);const has=p?.home_score!=null&&p?.away_score!=null;const a=has?(Number(p.home_score)>Number(p.away_score)?"home":Number(p.home_score)<Number(p.away_score)?"away":"draw"):null;const lab=t=>t==="underdog"?"Underdog":"Favoritt";return `<details class="points-explainer"><summary>ⓘ Se hva du kan få i poeng</summary><div class="points-explainer__body">${prow(`Vedder du på ${m.home_team}`,lab(x.homeType),x.home,a==="home")}${prow("Vedder du på uavgjort","Uavgjort",x.draw,a==="draw")}${prow(`Vedder du på ${m.away_team}`,lab(x.awayType),x.away,a==="away")}</div></details>`}
function card(m){const r=state.rounds.find(x=>x.id===m.round_id),p=state.predictions.get(m.id),o=open(m,r),saving=state.saving.has(m.id),rich=state.bonusPicks.get(key(m.id,"goal-rich"))===true,poor=state.bonusPicks.get(key(m.id,"goal-poor"))===true;return `<article class="tips-match ${o?"":"tips-match--locked"}" data-match-id="${m.id}"><div class="tips-match__meta"><span>${m.round||r?.name||"Kamp"}</span><time>${formatKickoff(m.kickoff_at)}</time></div><div class="tips-match__teams"><div>${tier(m.home_tier)}<strong>${countryCodeToFlag(m.home_country_code)} ${m.home_team}</strong></div><div class="tips-score"><input type="number" min="0" max="30" data-score-home value="${p?.home_score??""}" ${o?"":"disabled"}/><span>–</span><input type="number" min="0" max="30" data-score-away value="${p?.away_score??""}" ${o?"":"disabled"}/></div><div><strong>${m.away_team} ${countryCodeToFlag(m.away_country_code)}</strong>${tier(m.away_tier)}</div></div>${explain(m,p)}<div class="match-bonus-picks"><label class="${rich?"is-selected":""}"><input type="checkbox" data-match-bonus="goal-rich" ${rich?"checked":""} ${o?"":"disabled"}/><span>🔥 Målrik (${count("goal-rich")}/5)</span><small>4+ mål · riktig valg gir 1 poeng</small></label><label class="${poor?"is-selected":""}"><input type="checkbox" data-match-bonus="goal-poor" ${poor?"checked":""} ${o?"":"disabled"}/><span>🧊 Målfattig (${count("goal-poor")}/5)</span><small>0–1 mål · riktig valg gir 1 poeng</small></label></div><div class="tips-match__footer"><span class="tips-match__status">${saving?"Lagrer …":!o?"🔒 Tips stengt":p?"✓ Lagret":"Ikke lagret"}</span></div></article>`}
function tabs(){return `<div class="tips-rounds">${state.rounds.map(r=>`<button type="button" class="${r.id===state.selectedRoundId?"is-active":""}" data-round-id="${r.id}">${r.name}<small>${r.status==="open"?"Åpen":r.status}</small></button>`).join("")}</div>`}
function render(){const t=document.querySelector("#tips-content");if(!t)return;t.innerHTML=`${tabs()}<div class="tips-summary tips-summary--extended"><span><strong>${state.predictions.size}</strong> lagrede tips</span><span><strong>${count("goal-rich")}/5</strong> målrike</span><span><strong>${count("goal-poor")}/5</strong> målfattige</span></div><div class="tips-match-list">${state.matches.length?state.matches.map(card).join(""):`<div class="tips-empty">Ingen kamper ennå.</div>`}</div>`;bind();}
async function selectRound(id){state.selectedRoundId=id;state.matches=await getMatchesForRound(state.tournament.id,id);render();}
function saveLater(id,h,a){const old=state.timers.get(id);if(old)clearTimeout(old);state.timers.set(id,setTimeout(async()=>{state.saving.add(id);render();try{await savePrediction(id,h,a);state.predictions.set(id,{match_id:id,home_score:Number(h),away_score:Number(a)});}finally{state.saving.delete(id);state.timers.delete(id);render();}},650));}
function bind(){document.querySelectorAll("[data-round-id]").forEach(b=>b.onclick=()=>selectRound(b.dataset.roundId));document.querySelectorAll("[data-match-id]").forEach(c=>{const id=c.dataset.matchId,h=c.querySelector("[data-score-home]"),a=c.querySelector("[data-score-away]");[h,a].forEach(i=>i?.addEventListener("input",()=>{if(h.value===""||a.value==="")return;state.predictions.set(id,{match_id:id,home_score:Number(h.value),away_score:Number(a.value)});saveLater(id,h.value,a.value);}));c.querySelectorAll("[data-match-bonus]").forEach(ch=>ch.onchange=async()=>{const code=ch.dataset.matchBonus,sel=ch.checked,other=code==="goal-rich"?"goal-poor":"goal-rich";try{await setMatchBonusPick(id,code,sel);state.bonusPicks.set(key(id,code),sel);if(sel)state.bonusPicks.set(key(id,other),false);render();}catch(e){ch.checked=!sel;c.querySelector(".tips-match__status").textContent=e.message;}})});}
export async function TipsPage(){const a=getAuthSnapshot();if(!a.isAuthenticated)return `<div class="page"><section class="access-card"><span>⚽</span><h1>Logg inn for å tippe</h1><a class="button button--primary" href="/login" data-link>Logg inn</a></section></div>`;const tournament=await getActiveTournament();const[rounds,preds,rules,picks]=await Promise.all([getTournamentRounds(tournament.id),getMyPredictions(tournament.id),getActiveScoreRules(tournament.id),getMyMatchBonusPicks(tournament.id)]);const sr=rounds.find(r=>r.status==="open")||rounds[0];const matches=sr?await getMatchesForRound(tournament.id,sr.id):[];state={tournament,rounds,selectedRoundId:sr?.id??null,matches,predictions:new Map(preds.map(x=>[x.match_id,x])),bonusPicks:new Map(picks.map(x=>[key(x.match_id,x.bonus_code),true])),scoreRules:rules,saving:new Set(),timers:new Map()};setTimeout(render,0);return `<div class="page tips-page"><header class="page-header"><span>${tournament.short_name}</span><h1>Mine tips</h1><p>Tipsene er hemmelige frem til fristen. Folkets tips røpes først når kampen er låst.</p></header><section id="tips-content"></section></div>`;}
