import { getAuthSnapshot } from "../../services/auth-service.js";
import { getActiveTournament } from "../../repositories/tournament-repository.js";
import { getAdminPaymentOverview,updateMemberPayment,getBuyInPools } from "../../repositories/payment-repository.js";
let state={tournament:null,players:[],pools:[]};
function pools(){return `<section class="payment-pools">${[200,400,600,800].map(t=>{const p=state.pools.find(x=>Number(x.buy_in_tier)===t);return `<article><span>${t} kr-puljen</span><strong>${Number(p?.prize_pool||0).toLocaleString("no-NO")} kr</strong><small>${p?.paid_players||0} betalte</small></article>`}).join("")}</section>`}
function row(p){return `<article class="payment-row" data-payment-player="${p.player_id}"><div class="payment-row__player">${p.avatar_url?`<img src="${p.avatar_url}" alt=""/>`:`<span>${p.display_name.slice(0,1).toUpperCase()}</span>`}<strong>${p.display_name}</strong></div><select data-field="buyInTier"><option value="">Ingen pulje</option>${[200,400,600,800].map(t=>`<option value="${t}" ${Number(p.buy_in_tier)===t?"selected":""}>${t} kr</option>`).join("")}</select><select data-field="paymentStatus"><option value="pending" ${p.payment_status==="pending"?"selected":""}>Venter</option><option value="paid" ${p.payment_status==="paid"?"selected":""}>✓ Betalt</option><option value="waived" ${p.payment_status==="waived"?"selected":""}>Fritatt</option></select><input data-field="paidAmount" type="number" min="0" step="100" value="${p.paid_amount||0}"/><input data-field="paymentNote" type="text" value="${p.payment_note||""}" placeholder="Notat"/><button class="button button--primary" type="button" data-save-payment>Lagre</button><small class="payment-row__message"></small></article>`}
function render(){const t=document.querySelector("#payments-content");if(!t)return;t.innerHTML=`${pools()}<section class="payment-list">${state.players.map(row).join("")}</section>`;bind();}
function bind(){document.querySelectorAll("[data-save-payment]").forEach(b=>b.addEventListener("click",async()=>{const r=b.closest("[data-payment-player]");const v=n=>r.querySelector(`[data-field="${n}"]`)?.value??"";const m=r.querySelector(".payment-row__message");b.disabled=true;b.textContent="Lagrer …";try{await updateMemberPayment({tournamentId:state.tournament.id,playerId:r.dataset.paymentPlayer,buyInTier:Number(v("buyInTier"))||null,paymentStatus:v("paymentStatus"),paidAmount:Number(v("paidAmount")||0),paymentNote:v("paymentNote")});[state.players,state.pools]=await Promise.all([getAdminPaymentOverview(state.tournament.id),getBuyInPools(state.tournament.id)]);render();}catch(e){m.textContent=e.message;m.classList.add("is-error")}finally{b.disabled=false;b.textContent="Lagre"}}));}
export async function PaymentsPage(){const a=getAuthSnapshot();if(!a.isAdmin)return `<div class="page"><section class="access-card"><span>⛔</span><h1>Ingen tilgang</h1><p>Betalinger kan bare administreres av admin eller owner.</p><a class="button button--ghost" href="/" data-link>Til forsiden</a></section></div>`;const tournament=await getActiveTournament();const[players,poolsData]=await Promise.all([getAdminPaymentOverview(tournament.id),getBuyInPools(tournament.id)]);state={tournament,players,pools:poolsData};setTimeout(render,0);return `<div class="page"><header class="page-header"><span>Admin · ${tournament.short_name}</span><h1>Betalinger</h1><p>Velg pulje og marker spillerne som betalt.</p></header><section id="payments-content"></section></div>`;}
